apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: fl-server
  name: fl-extractor
spec:
  containers:
    - args:
        - python3
        - -m
        - fltk
        - single
        - configs/local_experiment.yaml
        - --rank=0
      env:
        - name: MASTER_PORT
          value: "5000"
        - name: PYTHONUNBUFFERED
          value: "1"
      image: gcr.io/cs4290-dml/fltk:latest
      name: federation-lab-server
      ports:
        - containerPort: 5000
      resources: {}
      volumeMounts:
        - mountPath: /opt/federation-lab/output
          name: fl-server-claim
  restartPolicy: Never
  volumes:
    - name: fl-server-claim
      persistentVolumeClaim:
        claimName: fl-server-claim
status: {}
