apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    srv.fltk.extractor: fl-extractor
  name: fl-extractor
spec:
  containers:
    - name: federation-lab-server
      args:
        - tensorboard
        - --logdir
        - logging
      image: "{{ .Values.provider.domain }}/{{ .Values.provider.projectName }}/{{ .Values.provider.imageName }}"
      ports:
        - containerPort: 8443
      resources:
        # Set the following values in case you want to limit the reserved resources.
        # Whenever the pod exceeds these requirements, the Scheduler (Kubernetes) may kill
        # the pod, resulting in startup.
        requests: {}
        limits: {}
      volumeMounts:
        - mountPath: /opt/federation-lab/output
          name: fl-server-claim
          readOnly: true                      # We mount output readOnly as this is for Orchestrator data.
        - mountPath: /opt/federation-lab/logging
          name: fl-log-claim
          readOnly: true                      # We mount log readOnly as this is for the Master worker nodes.
  restartPolicy: OnFailure                    # Whenever the container crashes, restart.
  volumes:
    - name: fl-server-claim
      persistentVolumeClaim:
        claimName: fl-server-claim
    - name: fl-log-claim
      persistentVolumeClaim:
        claimName: fl-log-claim
