---
# Experiment configuration
# Experiment configuration
total_epochs: 5
epochs_per_cycle: 1
wait_for_clients: true
net: Cifar10CNN
dataset: cifar10
sampler: "uniform"
sampler_args:
  - 0.5     # p degree
  - 42      # random seed
# Use cuda is available; setting to false will force CPU
cuda: false
experiment_prefix: 'experiment_single_machine'
output_location: 'output'
tensor_board_active: true
clients_per_round: 1
system:
  federator:
    hostname: '172.18.0.2'
    nic: 'eth0'
  clients:
    amount: 1
# For a simple config is provided in configs/poison.example.yaml
poison:
  seed: 420
  experiments:
    min_ratio: 0.0
    max_ratio: 0.25
    steps: 2
  attack:
    type: "timed"
    config: [ { 0:9, 9:0 } ]
    scenario:
      start_round: 0
      end_round: 10
      alpha: 0.5